Story7/urls.py
from django.urls import path

from . import views

app_name = 'Story7'

urlpatterns = [
    path('', views.index, name='index'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.jsoncall, name='search'),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.logging_in, name='login'),
    path('logout/', views.logging_out, name='logout'),
]

web_baru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

Story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Story7/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/story7.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests, json

# Create your views here.

def index(request):
	return render(request, 'story8/story8.html')

def jsoncall(request):
	url = 'https://www.googleapis.com/books/v1/volumes?q=' + request.GET['q']
	ret = requests.get(url)
	# print(url)
	# print(ret)
	data = json.loads(ret.content)
	return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
# Create your views here.

def index(request):
	return render(request, 'story9/story9.html')


def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('story9:index')
	else:
		form = UserCreationForm()
	return render(request, 'story9/signup.html', {'form': form})

def logging_in(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		login(request, user)
		return redirect('story9:index')
	else:
		return render(request, 'story9/login.html')

def logging_out(request):
	logout(request)
	return redirect('story9:index')

Story7/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  {% block styles %}{% endblock %}
  <link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Open+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

    
  <title>{% block title %}{% endblock %}</title>

</head>
<body class="bg-bisque">

    <nav class="navbar navbar-expand-lg navbar-dark bg-prus-blue">
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
    		<div class="navbar-nav">
      			<a class="nav-item nav-link font-cursive" href="{% url 'Story7:index' %}">Story 7</a>
      			<a class="nav-item nav-link font-cursive" href="{% url 'story8:index' %}">Story 8</a>
      			<a class="nav-item nav-link font-cursive" href="{% url 'story9:index' %}">Story 9</a>
      			<a class="nav-item nav-link font-cursive" href="#">Story 10</a>
    		</div>
  		</div>
	</nav>

	{% block content %}
	{% endblock %}

<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

Story7/templates/home/story7.html
{% extends 'home/base.html' %}
{% load static %}

{% block styles %}


{% endblock %}
{% block title %}Story 7 nya Ediw{% endblock %}

{% block content %}

	<div class="container mt-4 mb-4">
		<h1 class="text-center mb-5 font-cursive">my portofolio in an accordion</h1>
		<ul class="accordion">
		  <li>
		  	<div>
		    	<a class="toggle" href=#>Me</a>
		    	<button class="down float-right mx-2"><i class="fas fa-chevron-circle-down"></i></button>
				<button class="up float-right mx-2"><i class="fas fa-chevron-circle-up"></i></button>
		    </div>
		    <div class="inner">
		    	<img src="{% static 'home/img/potoalay.jpg' %}">
		    	<p>Alif Iqbal Hazairin</p>
		    	<p>Computer Science Student at University of Indonesia</p>
		    </div>
		  </li>
		  
		  <li>
		  	<div>
		    	<a class="toggle" href=#>Activities</a>
		    	<button class="down float-right mx-2"><i class="fas fa-chevron-circle-down"></i></button>
				<button class="up float-right mx-2"><i class="fas fa-chevron-circle-up"></i></button>
		    </div>
		    <div class="inner">
		      	<p>Currently serving as Head of Mushola Prosperity Department of FUKI 2020</p>
		      	<p>Studying, of course</p>
		    </div>
		  </li>
		  
		  <li>
		  	<div>
		    	<a class="toggle" href=#>Experience</a>
		    	<button class="down float-right mx-2"><i class="fas fa-chevron-circle-down"></i></button>
				<button class="up float-right mx-2"><i class="fas fa-chevron-circle-up"></i></button>
		    </div>
		    <div class="inner">
		      	<p>I was the Event Manager of my High School's third biggest competition</p>
		      	<p>Was a Staff of Logistics in Pemira IKM Fasilkom in 2019</p>
		      	<p>and staff of Consumption division in Wisuda Ganjil Fasilkom 2019</p>
		    </div>
		  </li>
		  
		  <li>
		  	<div>
		    	<a class="toggle" href=#>Achievements</a>
		    	<button class="down float-right mx-2"><i class="fas fa-chevron-circle-down"></i></button>
				<button class="up float-right mx-2"><i class="fas fa-chevron-circle-up"></i></button>
		    </div>
		    <div class="inner">
		      	<p>Bronze medalist in Interactive Meteorology at Pesta Sains Nasional held by IPB</p>
		      	<p>Participant of National Olympiad in Earth Science Field on 2018</p>
		      	<p>Surviving in Fasilkom until now (it's tough for real)</p>
		    </div>
		  </li>

		  <li>
			<div>
		    	<a class="toggle" href=#>Contacts</a>
		    	<button class="down float-right mx-2"><i class="fas fa-chevron-circle-down"></i></button>
				<button class="up float-right mx-2"><i class="fas fa-chevron-circle-up"></i></button>
		    </div>
		    <div class="inner">
		      	<a href="https://twitter.com/ediwhz" target="_blank">Twitter</a>
				<br>
				<a href="https://www.instagram.com/e___diw/" target="_blank">Instagram</a>
		    </div>
		  </li>
		</ul>

		<!-- <div class="accordion"> -->

		<!-- <div class="accordion-container border-top border-bottom">
				<div class="card-header title font-serif-custom bg-bisque">
					<a href="" class="toggle stretched-link">Me</a>
					<button class="down float-right mx-2"><i class="fas fa-chevron-circle-down"></i></button>
					<button class="up float-right mx-2"><i class="fas fa-chevron-circle-up"></i></button>
				</div>
				<div class="font-serif-custom">
					<p>Alif Iqbal Hazairin</p>
					<p>Ilmu Komputer - Fasilkom UI</p>
				</div>
			</div>
		</div> -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'home/scripts/script.js' %}"></script>

{% endblock %}

story8/templates/story8/story8.html
{% extends 'home/base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'story8/css/styles.css' %}">
{% endblock %}

{% block title %}Story 8 nya Ediw{% endblock %}

{% block content %}
<div class="container mt-4 mb-4">
	<h1 class="text-center mb-3 font-cursive">looking for books?</h1>
	<h3 class="text-center mb-4 font-cursive">find it here</h3>
	<div class="text-center">
		<input id="search" placeholder="masukkan keyword">
	</div>
	<ul id="list-of-content">
	<!-- Ini template nya ya 
		<li>
			<div class="content">
				<div class="image" id="image">
					<img src="http://books.google.com/books/content?id=2lOhCgAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api">
				</div>
				<div class="detail" id="detail">
					<a href="" target="_blank"><h4>Judul</h4></a>
					<hr>
					<h6>Author</h6>
					<div id="desc">
						<p>Deskripsi</p>
					</div>
				</div>
			</div>
		</li> 
	-->
	</ul>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'story8/scripts/scripts.js' %}"></script>
{% endblock %}

story9/templates/story9/login.html
{% extends 'home/base.html' %}
{% load static %}

{% block styles %}
<style>
  .btn-login {
    color: white;
    background-color: #e6703d;
    border-color: #e6703d;
  }
  input {
    width: 20%;
    padding: 10px 8px;
    /*border-radius: 15px;*/
    box-sizing: border-box;
    display: block;
  }
  input:focus {
    border: 2px solid #555;
  }
  form div {
    margin: 15px 0;
  }
</style>

{% endblock %}

{% block title %}login ya?{% endblock %}

{% block content %}
<div class="container mt-3 pl-auto">
  <h2 class="font-serif-custom">Log In</h2>
  <form method="POST">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="" id="username" name="username" placeholder="ur username" required>
    <br>
    <label for="pasword">Password: </label>
    <input type="password" id="password" name="password" placeholder="password please" required>
    <br>
    <div>
      <a href="/story9" type="button" class="btn btn-default">Cancel</a>
      <button type="submit" class="btn btn-login">Log In</button>
    </div>
  </form>
</div>
{% endblock %}

story9/templates/story9/signup.html
{% extends 'home/base.html' %}
{% load static %}

{% block styles %}
<style>
	.btn-sign-up {
		color: white;
		background-color: #e6703d;
		border-color: #e6703d;
	}
</style>
{% endblock %}

{% block title %}Sign Up duls{% endblock %}

{% block content %}
<div class="container mt-3">
	<h2 class="font-serif-custom">Sign Up</h2>
	<form method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
	<a href="/story9" type="button" class="btn btn-default">Cancel</a>
    <button type="submit" class="btn btn-sign-up">Sign up</button>
	</form>
</div>
{% endblock %}

story9/templates/story9/story9.html
{% extends 'home/base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'story9/css/style.css' %}">
{% endblock %}

{% block title %}Story 9 Ediw{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<div class="mt-5 mb-4 text-center">
	<p class="font-cursive" style="font-size: 50px;">Selamat Datang,</p>
	<p class="font-serif-custom" style="font-size: 30px;">{{ request.user.username }}</p>
	<p class="font-serif-custom" id="logout">Mau <a href="/story9/logout/">logout</a>?</p>
</div>
{% else %}
<div class="container mt-5 mb-4 text-center font-serif-custom">
	<p>Login <a href="/story9/login/">disini!</a></p>
	<p>Belum punya akun? <a href="/story9/signup/" style="color: #007bff;">Sign Up</a></p>
</div>
{% endif %}
{% endblock %}